version: "3.8"

services:
  mysql-db:
    image: mysql:8.0.27
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - mod-disc-bot_bot-network
    env_file:
      - mysql.env

  adminer-mysql:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - mod-disc-bot_bot-network
    ports:
      - 8080:8080

networks:
  mod-disc-bot_bot-network:
    external: true

volumes:
  mysqldata:
    driver: local